# Generated by Django 5.2.5 on 2025-08-26 11:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero_section', 5), ('rich_text', 6), ('image', 7), ('features', 13), ('testimonials', 19), ('contact_form', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title', 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle under the main title'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'help_text': 'Button text', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button link', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('button_text', 2), ('button_url', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Rich Text'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Feature title', 'max_length': 100}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Feature description'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon name (e.g.: star, heart, rocket)', 'max_length': 50}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for the feature', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('icon', 10), ('image', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'icon': 'list-ul', 'label': 'Features List'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Customer name', 'max_length': 100}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position or company', 'max_length': 100}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Review text'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Customer photo', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('name', 14), ('position', 15), ('text', 16), ('avatar', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'icon': 'user', 'label': 'Testimonials List'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Contact Us', 'help_text': 'Form title', 'max_length': 100}), 21: ('wagtail.blocks.TextBlock', (), {'help_text': 'Form description', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Send', 'help_text': 'Submit button text', 'max_length': 50}), 23: ('wagtail.blocks.StructBlock', [[('title', 20), ('description', 21), ('submit_button_text', 22)]], {})}, help_text='Add various content blocks'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief company introduction'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords separated by commas', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description for search engines', max_length=160),
        ),
    ]
